Add possibility to check contracts in a batch
lidofinance/diffyscan pull request #3
Opened 2023-04-25 15:56 UTC by folkyatina

2023-04-25 16:35 UTC, TheDZhon requested changes
LGTM except only a few things :+1:

2023-04-25 16:35 UTC, TheDZhon commented on main.py
> +    if contract_address is not None:
let's log the chosen mode explicitly

2023-04-25 16:35 UTC, TheDZhon commented on config.sample.json
> +        "@aragon": "https://github.com/aragon/aragonOS/tree/v4.4.0",
We use `4.4.1`
https://github.com/lidofinance/lido-dao/blob/master/package.json#L120

2023-04-26 08:41 UTC, mymphe approved these changes

2023-04-26 08:42 UTC, mymphe commented
LGTM

2023-04-26 08:42 UTC, merged