build: make installable via poetry / pipx
lidofinance/diffyscan pull request #47
Opened 2024-06-03 08:59 UTC by madlabman

2024-06-03 09:04 UTC, mymphe approved these changes
Awesome feature!

2024-06-03 09:22 UTC, TheDZhon requested changes
Thank you for the great proposal!

I'd suggest addressing only a single suggestion regarding the version bookkeeping approach to make it more robust.

2024-06-03 09:22 UTC, TheDZhon commented on pyproject.toml
> +version = "0.1.0"
Sorry, but if we want to package it, then I would plug the automated versioned builds here:

```toml
version = "0.0.0"

# ...

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
metadata = false

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.1.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
```

2024-06-03 09:22 UTC, TheDZhon commented on pyproject.toml
> +version = "0.1.0"
Also, please consider adding a command line argument to retrieve the version upon launch.

2024-06-04 09:05 UTC, skhomuti approved these changes

2024-06-05 05:47 UTC, TheDZhon approved these changes
Awesome work, merging to the upstream :+1:

2024-06-05 05:47 UTC, merged