Cfg/optimism testnet fix
lidofinance/diffyscan pull request #68
Opened 2024-11-07 10:56 UTC by kovalgek

2025-01-13 10:42 UTC, tamtamchik approved these changes
Looks good, but have some suggestions.

2025-01-13 10:42 UTC, tamtamchik commented on diffyscan/diffyscan.py
> +    logger.okay("Blockchain explorer Hostname", get_explorer_hostname(config))
Store the result in a variable so the function doesn't need to be run a second time, or see comment below

2025-01-13 10:42 UTC, tamtamchik commented on diffyscan/diffyscan.py
> +        f"Fetching source code from blockchain explorer {get_explorer_hostname(config)} ..."
Do we need this log at all? We have already logged Blockchain explorer above in the code.

2025-01-13 10:42 UTC, tamtamchik commented on diffyscan/diffyscan.py
> +def get_explorer_hostname(config):
Maybe move to utils/explorer?

2025-01-13 10:42 UTC, tamtamchik commented on diffyscan/utils/hardhat.py
> +            if "WILL BE LOST" in output:
convert both strings to same case to make the check more stable?

2025-01-13 10:42 UTC, tamtamchik commented on package.json
> +    "hardhat": "^2.22.15",
The latest HH is 2.22.17

2025-01-13 17:54 UTC, arwer13 requested changes

2025-01-13 17:54 UTC, arwer13 commented on config_samples/optimism/automaton/automaton_config_L1.json
> +{
I think the configs shouldn't be located in the repo but automaton's repo. Contract addresses make no sense here

2025-01-16 12:56 UTC, arwer13 approved these changes

2025-01-16 13:11 UTC, merged